#! /bin/bash


# work in this directory
pushd `dirname $0` > /dev/null 2>&1;


: ${APP_NAME:=hazdev-app}
: ${MOUNT_PATH:=/mount/path}
# these usually use defaults
: ${APP_DIR:=/data/www/apps/${APP_NAME}}
: ${HTDOCS_DIR:=${APP_DIR}/htdocs}
: ${HTTPD_CONF:=${APP_DIR}/conf/httpd.conf}


# generate httpd.conf
cat > ${HTTPD_CONF} <<-EOF
	Alias ${MOUNT_PATH} ${HTDOCS_DIR}

	<Directory ${HTDOCS_DIR}>
		Require method GET OPTIONS

		ExpiresActive on
		ExpiresDefault "access plus 1 day"

		SetEnv MOUNT_PATH ${MOUNT_PATH}

		# todo: add rewrite examples
	</Directory>
EOF


popd > /dev/null 2>&1;
exit 0;
