#!/usr/bin/env bash

push `dirname $0` > /dev/null 2>&1;


: ${APP_NAME:=hazdev-app}
: ${MOUNT_PATH:=/mount/path}
# these usually use defaults
: ${APP_DIR:=/data/www/apps/${APP_NAME}}
: ${HTDOCS_DIR:=${APP_DIR}/htdocs}
: ${HTTPD_CONF:=${APP_DIR}/conf/httpd.conf}


# Remove httpd config file, but leave the config INI file in place
rm -vf "${HTTPD_CONF}"


popd > /dev/null 2>&1;

exit 0;
